name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build and install
        run: pip install --verbose .

      - name: Test
        run: |
          pip install pytest
          pytest tests

  build-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-python-wheel
            mingw-w64-x86_64-cmake

      - uses: actions/checkout@v4
      - name: Fix SSL certificates
        run: |
          python -m pip install --upgrade certifi
          export SSL_CERT_FILE=$(python -m certifi)
        shell: bash

      - name: Create virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
        shell: bash

      - name: Install dependencies in virtual environment
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
        shell: bash

      - name: Build and install
        run: |
          source venv/bin/activate
          pip install --no-build-isolation .
        shell: bash

      - name: Test
        run: |
          source venv/bin/activate
          pytest tests/
        shell: bash
