name: Pip

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-13, macos-14, windows-latest]
        python-version: ["3.11"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build and install
        run: pip install --verbose .

      - name: Test
        run: |
          pip install pytest
          pytest tests

  # build-mingw64:
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         update: true
  #         install: >-
  #           mingw-w64-x86_64-gcc
  #           mingw-w64-x86_64-python-pip
  #           mingw-w64-x86_64-python-wheel
  #           mingw-w64-x86_64-cmake

  #     - uses: actions/checkout@v4
  #     - name: Fix SSL certificates
  #       run: |
  #         python -m pip install --upgrade certifi
  #         export SSL_CERT_FILE=$(python -m certifi)
  #       shell: bash

  #     - name: Create and activate virtual environment
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate || venv/Scripts/activate

  #     - name: Install dependencies in virtual environment
  #       run: |
  #         venv/bin/python -m pip install --upgrade pip
  #         venv/bin/python -m pip install -r requirements.txt

  #     - name: Build and install
  #       # --no-build-isolation is required because the vanilla setuptool does not
  #       # support Mingw64.See patches here:
  #       # https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-python-setuptools
  #       # Without those patches build_ext fails with:
  #       # error: --plat-name must be one of ('win32', 'win-amd64', 'win-arm32', 'win-arm64')
  #       run: python -m pip install --no-build-isolation .

  #     - name: Test
  #       run: |
  #         venv/bin/python -m pip install pytest
  #         pytest tests/
